### ISSUE TITLE
Add the ability to query a single user album

### ISSUE THREAD

**Issue by aleccool213** [chrissearle/gatsby-source-flickr#2]

**Comment by chrissearle** [comment]
This is _almost_ possible already.

The start will be adding the following to gatsby-config:

```
    {
      resolve: 'gatsby-source-flickr',
      options: {
        api_key: YOUR_FLICKR_KEY,
        user_id: YOUR_FLICKR_USER,
        // Add the following lines
        method: 'flickr.photosets.getPhotos',
        photoset_id: NUMERIC_ID_OF_ALBUM,
      },
    },
```

However - there is one thing I have to change in code first - search returns this structure:

```
{
  "photos": {
    "photo": [ list of photos ],
}
```

getPhotos here returns this structure:

```
{
  "photoset": {
    "photo": [ list of photos ],
}
```

So - I need to make it cope with a different outer object name.

I'll try and look at this during the weekend.

**Comment by chrissearle** [comment]
Should be working in 0.0.2 (see readme for example)

**Comment by aleccool213** [comment]
Amazing, thanks for the quick response. This was the one thing blocking me from using this repo! 💯
