### ISSUE TITLE
Allow for multiple user_ids to be queried

### ISSUE THREAD

**Issue by Kadrei** [chrissearle/gatsby-source-flickr#3]
Currently, it is only allowed to set one `user_id` in the plugins options.

```
module.exports = {
  plugins: [
    {
      resolve: "gatsby-source-flickr",
      options: {
        user_id: process.env.FLICKR_USER_ID <---- only strings allowed
      }
    }
  ]
};
```

I have the need to extract the data from at least two different users, therefore, I either could not specify the `user_id` option at all and then specify them in queries or the functionality to specify multiple `user_id`s is added to the plugin.

Due to me also trying to integrate the Flickr Images with `gatsby-image` (Which downloads all specified nodes and caches them) I cannot use the second approach.

**Comment by Kadrei** [comment]
I just realized one can simply define multiple plugin entries with different `user_id`s - so it works out of the box. Thank you for the plugin :)

**Comment by chrissearle** [comment]
Ok - glad you found out about it. Not sure multiple users on the same call is even possible - from flicker’s API:

The NSID of the user who's photo to search. If this parameter isn't passed then everybody's public photos will be searched. A value of "me" will search against the calling user's photos for authenticated calls.
