### ISSUE TITLE
Publish 0.0.3

### ISSUE THREAD

**Issue by davepwsmith** [chrissearle/gatsby-source-flickr#4]
Hello there.

A recent update to core-js@3 in gatsby forced me to fork and build this to see if I could fix whatever was going wrong with the dependencies... and when I built it, it worked already! You should consider pushing a new version to npm so that the plugin continues to work. I think it's really just a case that the thing needs building again to drag in corejs3 on the polyfills, but can't see why you wouldn't also include the changes added since 0.0.2

Dave

**Comment by chrissearle** [comment]
I'll take a look - should have some time next week.

**Comment by chrissearle** [comment]
Ugh - I completely forgot about this - just fell off my radar - sorry.

Been so long since I looked at it I will have to remember how I build it.

**Comment by chrissearle** [comment]
Published a new version today. Somehow managed to skip 0.0.3 - so this arrived as 0.0.4. Works for my installation so I hope it helps.

Sorry again that it took so long 👍
